### ISSUE TITLE
Basic usage of the Mistral-7B LLM

### ISSUE THREAD

**Issue by 907Resident** [Overtrained/contextual-qa-chat-app#15]
## Context:

Since the [Mistral-7B](https://mistral.ai/news/announcing-mistral-7b/) was released in September, there has been a lot of discussion on how well this model is performing against other [open source models](https://www.unite.ai/wp-content/uploads/2023/09/mistral-ai-model.jpeg) and even [closed source models](https://eightify.app/summary/artificial-intelligence-and-machine-learning/mistral-ai-7b-vs-chatgpt-gpt-3-5-turbo-20-questions-comparison). 

## Objective:

Demonstrate the ability to download and utilize the Mistral-7B instruct [model](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1) on a reasonably sized compute set up. 

## Path to completion:

The following tasks will need to be completed to close this issue:
- [x] Successfully download the model in a Google Colab Pro GPU environment
- [x] Generate a basic output through a simple instruction
- [x] Report findings within notebook

## Related Tasks:

- #18

**Comment by 907Resident** [comment]
See commit 38259d7 for more guidance on future work

**Comment by mcnewcp** [comment]
~~How did you add tasks?  I like that.~~.  Nvm, found it.

**Comment by 907Resident** [comment]
A new branch called `exploring-mistral-for-rag` has been made and will be merged into this issue's branch when exploration is complete

**Comment by 907Resident** [comment]
Converted "Bonus Tasks" to "Related Tasks" to close this issue
