### ISSUE TITLE
Add context to chat bot

### ISSUE THREAD

**Issue by mcnewcp** [Overtrained/contextual-qa-chat-app#3]
# Summary
Add a vectorized database for context to the chat bot.  This can be done using a similarity search and appending context to the prompt, or by using a more direct QA retrieval chain from `langchain`.

# Dataset 
Some dataset idea resources:
- financial reddit data on [huggingface](https://huggingface.co/datasets/winddude/reddit_finance_43_250k)
- and the [repo](https://github.com/getorca/ProfitsBot_V0_OLLM/tree/main/ds_builder) used to create the dataset above, including rating, sorting, scoring, filtering
- reddit bulk downloader [repo](https://github.com/aliparlakci/bulk-downloader-for-reddit)
- pushshift reddit [archive](https://the-eye.eu/redarcs/).  This one has been put on hold as of 03/23
- [tutorial](https://huggingface.co/docs/datasets/tutorial) on huggingface datasets

# Technique
Trial the following Retrieval Augmented Generation (RAG) techniques:

1. `RetrievalQA` ([example 1](https://python.langchain.com/docs/use_cases/question_answering/), [example 2](https://python.langchain.com/docs/use_cases/question_answering/how_to/vector_db_qa), [streamlit example](https://blog.streamlit.io/langchain-tutorial-4-build-an-ask-the-doc-app/)) will execute one for one questions and answers on the embedded data source.
2. Add chat history - this builds on above by retaining history and allowing for a chat interaction ([`ConversationalRetrievalQA` example](https://python.langchain.com/docs/use_cases/question_answering/how_to/chat_vector_db), [manual example](https://www.dbdemos.ai/minisite/llm-dolly-chatbot/)).
3. Conversational Retrieval Agent ([example 1](https://python.langchain.com/docs/use_cases/question_answering/how_to/conversational_retrieval_agents), [blog post](https://blog.langchain.dev/conversational-retrieval-agents/)) improves on `ConversationalRetrievalQA` by more efficiently using chat history and also choosing when to query the data source and when not to.
4. Retrieval with metadata.  By including metadata in the index, the context can be improved by filtering on metadata prior to the semantic search.  Many popular vector dbs support metadata filters, and [LlamaIndex](https://www.llamaindex.ai) provides some tools for managing the metadata easily.  The metadata filters can be applied manually, or generated by the LLM ([Auto-Retrieval](https://docs.llamaindex.ai/en/stable/examples/vector_stores/chroma_auto_retriever.html)) or agent ([OpenAI Agent + Query Engine](https://docs.llamaindex.ai/en/stable/examples/agent/openai_agent_query_cookbook.html)).

**Comment by mcnewcp** [comment]
@907Resident FYI see above for a working summary of techniques to trial for question answering with context.

**Comment by 907Resident** [comment]
Nice, I will try some of these ideas out locally. I should be able to get at least one looked at today

Thanks for sharing
